// Extensive & Exhaustive Database of Indian Colleges, Universities & Institutes Across All States & UTs

export const INDIAN_COLLEGES = [
  // --- UTTAR PRADESH (UP) & LUCKNOW ---
  "University of Lucknow (Lucknow University), Lucknow",
  "AKTU - Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
  "KIET Group of Institutions, Ghaziabad",
  "AKGEC - Ajay Kumar Garg Engineering College, Ghaziabad",
  "JSS Academy of Technical Education, Noida",
  "Galgotias College of Engineering and Technology, Greater Noida",
  "Galgotias University, Greater Noida",
  "Amity University, Noida",
  "Jaypee Institute of Information Technology (JIIT), Noida",
  "Shiv Nadar University (SNU), Greater Noida",
  "Sharda University, Greater Noida",
  "GL Bajaj Institute of Technology and Management, Greater Noida",
  "ABES Engineering College, Ghaziabad",
  "IMS Engineering College, Ghaziabad",
  "NIET - Noida Institute of Engineering and Technology, Greater Noida",
  "IET Lucknow - Institute of Engineering and Technology, Lucknow",
  "HBTI - Harcourt Butler Technical University, Kanpur",
  "MMMUT - Madan Mohan Malaviya University of Technology, Gorakhpur",
  "BIET Jhansi - Bundelkhand Institute of Engineering and Technology",
  "GLA University, Mathura",
  "CSJM - Chhatrapati Shahu Ji Maharaj University, Kanpur",
  "MJPRU - Mahatma Jyotiba Phule Rohilkhand University, Bareilly",
  "CCSU - Chaudhary Charan Singh University, Meerut",
  "RMLAU - Dr. Ram Manohar Lohia Avadh University, Ayodhya",
  "MGKVP - Mahatma Gandhi Kashi Vidyapith, Varanasi",
  "Bundelkhand University, Jhansi",
  "Deen Dayal Upadhyaya Gorakhpur University (DDUGU), Gorakhpur",
  "Gautam Buddha University (GBU), Greater Noida",
  "University of Allahabad (Allahabad University), Prayagraj",
  "BBAU - Babasaheb Bhimrao Ambedkar University, Lucknow",
  "Dr. Shakuntala Misra National Rehabilitation University, Lucknow",
  "Integral University, Lucknow",
  "BBDU - Babu Banarasi Das University, Lucknow",
  "SRMU - Shri Ramswaroop Memorial University, Lucknow",
  "Era University, Lucknow",
  "Invertis University, Bareilly",
  "TMU - Teerthanker Mahaveer University, Moradabad",
  "Shobhit University, Meerut",
  "Rama University, Kanpur",
  "PSIT - Pranveer Singh Institute of Technology, Kanpur",
  "United College of Engineering and Research, Prayagraj",
  "KCC Institute of Technology and Management, Greater Noida",
  "ITS Engineering College, Greater Noida",
  "GNIOT - Greater Noida Institute of Technology, Greater Noida",
  "Mangalmay Institute of Engineering and Technology, Greater Noida",
  "IEC College of Engineering and Technology, Greater Noida",
  "BHU - Banaras Hindu University, Varanasi",
  "AMU - Aligarh Muslim University, Aligarh",
  "IIIT Allahabad - Indian Institute of Information Technology",
  "IIIT Lucknow - Indian Institute of Information Technology",
  "IIT Kanpur - Indian Institute of Technology",
  "IIT (BHU) Varanasi - Indian Institute of Technology",
  "IIM Lucknow - Indian Institute of Management",
  "KGMU - King George's Medical University, Lucknow",
  "SGPGI - Sanjay Gandhi Postgraduate Institute of Medical Sciences, Lucknow",
  "RMLIMS - Dr. Ram Manohar Lohia Institute of Medical Sciences, Lucknow",
  "GSVM Medical College, Kanpur",
  "LLRM Medical College, Meerut",
  "SN Medical College, Agra",
  "MLN Medical College, Prayagraj",
  "National P.G. College, Lucknow",
  "Isabella Thoburn College (IT College), Lucknow",
  "Lucknow Christian College, Lucknow",
  "Shri Ramswaroop Memorial Group of Professional Colleges (SRMGPC), Lucknow",
  "BBDNITM - Babu Banarasi Das Northern India Institute of Technology, Lucknow",
  "BNCET - BN College of Engineering and Technology, Lucknow",

  // --- DELHI NCR & DELHI UNIVERSITY (DU) ---
  "St. Stephen's College, Delhi University",
  "Hindu College, Delhi University",
  "Shri Ram College of Commerce (SRCC), Delhi University",
  "Miranda House, Delhi University",
  "Hansraj College, Delhi University",
  "Lady Shri Ram College for Women (LSR), Delhi University",
  "Kirori Mal College (KMC), Delhi University",
  "Sri Venkateswara College, Delhi University",
  "Atma Ram Sanatan Dharma College (ARSD), Delhi University",
  "Shaheed Sukhdev College of Business Studies (SSCBS), Delhi University",
  "Sri Guru Gobind Singh College of Commerce (SGGSCC), Delhi University",
  "Ramjas College, Delhi University",
  "Gargi College, Delhi University",
  "Sri Guru Tegh Bahadur Khalsa College, Delhi University",
  "Dyal Singh College, Delhi University",
  "Keshav Mahavidyalaya, Delhi University",
  "Kamala Nehru College, Delhi University",
  "Jesus and Mary College (JMC), Delhi University",
  "Maitreyi College, Delhi University",
  "Deshbandhu College, Delhi University",
  "Motilal Nehru College, Delhi University",
  "Ramanujan College, Delhi University",
  "Acharya Narendra Dev College (ANDC), Delhi University",
  "Deen Dayal Upadhyaya College (DDUC), Delhi University",
  "Delhi Technological University (DTU), Delhi",
  "Netaji Subhas University of Technology (NSUT), Delhi",
  "IIIT Delhi - Indraprastha Institute of Information Technology",
  "GGSIPU - Guru Gobind Singh Indraprastha University, Delhi",
  "MAIT - Maharaja Agrasen Institute of Technology, Delhi",
  "MSIT - Maharaja Surajmal Institute of Technology, Delhi",
  "BVCOE - Bharati Vidyapeeth's College of Engineering, Delhi",
  "BPIT - Bhagwan Parshuram Institute of Technology, Delhi",
  "USICT - University School of Information, Communication and Technology, Delhi",
  "IGDTUW - Indira Gandhi Delhi Technical University for Women",
  "Jamia Millia Islamia (JMI), New Delhi",
  "Jawaharlal Nehru University (JNU), New Delhi",
  "Jamia Hamdard, New Delhi",
  "IIT Delhi - Indian Institute of Technology",
  "AIIMS New Delhi - All India Institute of Medical Sciences",
  "Maulana Azad Medical College (MAMC), New Delhi",
  "VMMC - Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi",
  "Lady Hardinge Medical College (LHMC), New Delhi",
  "UCMS - University College of Medical Sciences, Delhi",
  "NIFT Delhi - National Institute of Fashion Technology",
  "NID Delhi - National Institute of Design",
  "VIPS - Vivekananda Institute of Professional Studies, Delhi",
  "ADGITM - Dr. Akhilesh Das Gupta Institute of Technology & Management, Delhi",
  "GTBIT - Guru Tegh Bahadur Institute of Technology, Delhi",

  // --- JHARKHAND & BIHAR ---
  "IIIT Ranchi - Indian Institute of Information Technology, Jharkhand",
  "BIT Mesra - Birla Institute of Technology, Ranchi",
  "IIT (ISM) Dhanbad - Indian Institute of Technology",
  "NIT Jamshedpur - National Institute of Technology",
  "XLRI - Xavier School of Management, Jamshedpur",
  "Ranchi University, Ranchi",
  "St. Xavier's College, Ranchi",
  "XISS - Xavier Institute of Social Service, Ranchi",
  "NUSRL - National University of Study and Research in Law, Ranchi",
  "Central University of Jharkhand (CUJ), Ranchi",
  "BIT Sindri, Dhanbad",
  "Vinoba Bhave University (VBU), Hazaribagh",
  "Sido Kanhu Murmu University (SKMU), Dumka",
  "IIT Patna - Indian Institute of Technology",
  "NIT Patna - National Institute of Technology",
  "IIIT Bhagalpur - Indian Institute of Information Technology",
  "Patna University, Patna",
  "Patna Science College, Patna",
  "Anugrah Narayan College (A.N. College), Patna",
  "Aryabhatta Knowledge University (AKU), Patna",
  "CUSB - Central University of South Bihar, Gaya",
  "Chanakya National Law University (CNLU), Patna",
  "NIFT Patna - National Institute of Fashion Technology",
  "AIIMS Patna - All India Institute of Medical Sciences",
  "PMCH - Patna Medical College and Hospital, Patna",
  "IGIMS - Indira Gandhi Institute of Medical Sciences, Patna",
  "MIT Muzaffarpur - Muzaffarpur Institute of Technology",
  "BCE Bhagalpur - Bhagalpur College of Engineering",
  "Darbhanga College of Engineering, Darbhanga",
  "Gaya College of Engineering, Gaya",
  "Magadh University, Bodh Gaya",

  // --- ALL OTHER IIITS (INDIAN INSTITUTES OF INFORMATION TECHNOLOGY) ---
  "IIIT Allahabad - Indian Institute of Information Technology",
  "IIIT Bangalore - International Institute of Information Technology",
  "IIIT Hyderabad - International Institute of Information Technology",
  "IIITM Gwalior - ABV-Indian Institute of Information Technology and Management",
  "IIITDM Jabalpur - Pandit Deendayal Upadhyaya IIITDM",
  "IIITDM Kancheepuram - IIITDM Kancheepuram",
  "IIITDM Kurnool - IIITDM Kurnool",
  "IIIT Pune - Indian Institute of Information Technology",
  "IIIT Nagpur - Indian Institute of Information Technology",
  "IIIT Kota - Indian Institute of Information Technology",
  "IIIT Vadodara - Indian Institute of Information Technology",
  "IIIT Surat - Indian Institute of Information Technology",
  "IIIT Una - Indian Institute of Information Technology, Himachal Pradesh",
  "IIIT Sonepat - Indian Institute of Information Technology",
  "IIIT Bhopal - Indian Institute of Information Technology",
  "IIIT Dharwad - Indian Institute of Information Technology",
  "IIIT Guwahati - Indian Institute of Information Technology",
  "IIIT Kalyani - Indian Institute of Information Technology, West Bengal",
  "IIIT Kottayam - Indian Institute of Information Technology, Kerala",
  "IIIT Manipur - Indian Institute of Information Technology",
  "IIIT Sri City - Indian Institute of Information Technology, Chittoor",
  "IIIT Agartala - Indian Institute of Information Technology",
  "IIIT Raichur - Indian Institute of Information Technology",
  "IIIT Trichy - Indian Institute of Information Technology, Tiruchirappalli",

  // --- GUJARAT & PANDIT DEENDAYAL INSTITUTES ---
  "Pandit Deendayal Energy University (PDEU / PDPU), Gandhinagar",
  "Dharmsinh Desai University (DDU), Nadiad",
  "IIT Gandhinagar - Indian Institute of Technology",
  "SVNIT Surat - Sardar Vallabhbhai National Institute of Technology",
  "Nirma University, Ahmedabad",
  "Gujarat University, Ahmedabad",
  "MSU - Maharaja Sayajirao University of Baroda, Vadodara",
  "DA-IICT - Dhirubhai Ambani Institute of Information and Communication Technology, Gandhinagar",
  "GTU - Gujarat Technological University, Ahmedabad",
  "Marwadi University, Rajkot",
  "Parul University, Vadodara",
  "Ahmedabad University, Ahmedabad",
  "IIM Ahmedabad - Indian Institute of Management",
  "MICA - Mudra Institute of Communications, Ahmedabad",
  "GNLU - Gujarat National Law University, Gandhinagar",
  "NID Ahmedabad - National Institute of Design",
  "BVM Engineering College, Vallabh Vidyanagar",
  "LD College of Engineering, Ahmedabad",

  // --- PUNJAB, HARYANA & CHANDIGARH ---
  "Panjab University (PU), Chandigarh",
  "PEC - Punjab Engineering College, Chandigarh",
  "Chandigarh University, Mohali",
  "Chitkara University, Rajpura Punjab",
  "Thapar Institute of Engineering and Technology (TIET), Patiala",
  "LPU - Lovely Professional University, Phagwara",
  "GNDU - Guru Nanak Dev University, Amritsar",
  "Punjabi University, Patiala",
  "IKPTU - I.K. Gujral Punjab Technical University, Jalandhar",
  "NIT Jalandhar - Dr B R Ambedkar National Institute of Technology",
  "AIIMS Bathinda - All India Institute of Medical Sciences",
  "IISER Mohali - Indian Institute of Science Education and Research",
  "NIPER Mohali - National Institute of Pharmaceutical Education and Research",
  "YMCA Faridabad - J.C. Bose University of Science and Technology",
  "DCRUST - Deenbandhu Chhotu Ram University of Science and Technology, Murthal",
  "Kurukshetra University, Kurukshetra",
  "MDU - Maharshi Dayanand University, Rohtak",
  "Gurugram University, Gurugram",
  "Ashoka University, Sonepat",
  "O.P. Jindal Global University, Sonepat",
  "BML Munjal University, Gurugram",
  "GD Goenka University, Gurugram",
  "NIT Kurukshetra - National Institute of Technology",
  "Manav Rachna International Institute of Research and Studies, Faridabad",
  "The NorthCap University, Gurugram",

  // --- RAJASTHAN & MADHYA PRADESH ---
  "MNIT Jaipur - Malaviya National Institute of Technology",
  "BITS Pilani - Birla Institute of Technology and Science, Pilani",
  "Manipal University Jaipur",
  "LNMIIT - LNM Institute of Information Technology, Jaipur",
  "University of Rajasthan, Jaipur",
  "RTU - Rajasthan Technical University, Kota",
  "MBM Engineering College, Jodhpur",
  "CTAE - College of Technology and Engineering, Udaipur",
  "Banasthali Vidyapith, Rajasthan",
  "Central University of Rajasthan, Ajmer",
  "IIT Jodhpur - Indian Institute of Technology",
  "AIIMS Jodhpur - All India Institute of Medical Sciences",
  "IIM Udaipur - Indian Institute of Management",
  "NLU Jodhpur - National Law University",
  "Poornima University, Jaipur",
  "JK Lakshmipat University, Jaipur",
  "SKIT - Swami Keshvanand Institute of Technology, Jaipur",
  "IIT Indore - Indian Institute of Technology",
  "IIM Indore - Indian Institute of Management",
  "MANIT Bhopal - Maulana Azad National Institute of Technology",
  "RGPV - Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal",
  "DAVV - Devi Ahilya Vishwavidyalaya, Indore",
  "Barkatullah University, Bhopal",
  "Jiwaji University, Gwalior",
  "RDVV - Rani Durgavati Vishwavidyalaya, Jabalpur",
  "LNCT - Lakshmi Narain College of Technology, Bhopal",
  "Acropolis Institute of Technology and Research, Indore",
  "Prestige Institute of Management and Research, Indore",
  "NLIU Bhopal - National Law Institute University",
  "AIIMS Bhopal - All India Institute of Medical Sciences",

  // --- MAHARASHTRA ---
  "Mumbai University - University of Mumbai, Mumbai",
  "VJTI Mumbai - Veermata Jijabai Technological Institute",
  "ICT Mumbai - Institute of Chemical Technology",
  "St. Xavier's College, Mumbai",
  "NMIMS - Narsee Monjee Institute of Management Studies, Mumbai",
  "D.J. Sanghvi College of Engineering, Mumbai",
  "SPIT - Sardar Patel Institute of Technology, Mumbai",
  "COEP Technological University, Pune",
  "MIT-WPU - MIT World Peace University, Pune",
  "VIT Pune - Vishwakarma Institute of Technology",
  "PICT - Pune Institute of Computer Technology",
  "Symbiosis International University, Pune",
  "Savitribai Phule Pune University (SPPU), Pune",
  "VNIT Nagpur - Visvesvaraya National Institute of Technology",
  "RCOEM - Shri Ramdeobaba College of Engineering and Management, Nagpur",
  "YCCE - Yeshwantrao Chavan College of Engineering, Nagpur",
  "Government College of Engineering, Aurangabad",
  "Government College of Engineering, Karad",
  "Walchand College of Engineering (WCE), Sangli",
  "TISS - Tata Institute of Social Sciences, Mumbai",
  "IIM Mumbai (formerly NITIE), Mumbai",
  "AFMC - Armed Forces Medical College, Pune",
  "Grant Medical College and Sir JJ Group of Hospitals, Mumbai",
  "KEM Hospital and Seth GS Medical College, Mumbai",

  // --- KARNATAKA & SOUTH INDIA ---
  "IISc - Indian Institute of Science, Bengaluru",
  "NITK Surathkal - National Institute of Technology Karnataka",
  "RVCE - RV College of Engineering, Bengaluru",
  "BMSCE - BMS College of Engineering, Bengaluru",
  "MSRIT - Ramaiah Institute of Technology, Bengaluru",
  "PES University, Bengaluru",
  "Dayananda Sagar College of Engineering, Bengaluru",
  "Christ University, Bengaluru",
  "St. Joseph's University, Bengaluru",
  "Mount Carmel College, Bengaluru",
  "NLSIU - National Law School of India University, Bengaluru",
  "MAHE - Manipal Academy of Higher Education, Manipal",
  "MIT Manipal - Manipal Institute of Technology",
  "Bangalore University, Bengaluru",
  "VTU - Visvesvaraya Technological University, Belagavi",
  "IIM Bangalore - Indian Institute of Management",
  "IIT Madras - Indian Institute of Technology",
  "NIT Trichy - National Institute of Technology Tiruchirappalli",
  "VIT Vellore - Vellore Institute of Technology",
  "VIT Chennai - Vellore Institute of Technology",
  "SRM Institute of Science and Technology, Kattankulathur",
  "SRM University, Ramapuram",
  "Anna University, Chennai",
  "PSG College of Technology, Coimbatore",
  "SSN College of Engineering, Chennai",
  "Loyola College, Chennai",
  "Madras Christian College (MCC), Chennai",
  "SASTRA Deemed University, Thanjavur",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Sathyabama Institute of Science and Technology, Chennai",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute, Chennai",
  "CMC Vellore - Christian Medical College",
  "Madras Medical College (MMC), Chennai",
  "NIT Calicut - National Institute of Technology Calicut",
  "IIT Palakkad - Indian Institute of Technology",
  "CUSAT - Cochin University of Science and Technology, Kochi",
  "CET - College of Engineering Trivandrum",
  "IIST - Indian Institute of Space Science and Technology, Thiruvananthapuram",
  "University of Kerala, Thiruvananthapuram",
  "IIM Kozhikode - Indian Institute of Management",
  "IIT Hyderabad - Indian Institute of Technology",
  "Osmania University, Hyderabad",
  "JNTU Hyderabad - Jawaharlal Nehru Technological University",
  "CBIT - Chaitanya Bharathi Institute of Technology, Hyderabad",
  "VNR VJIET - VNR Vignana Jyothi Institute of Engineering and Technology, Hyderabad",
  "BITS Pilani, Hyderabad Campus",
  "Mahindra University, Hyderabad",
  "NIT Warangal - National Institute of Technology",
  "Andhra University, Visakhapatnam",
  "IIT Tirupati - Indian Institute of Technology",
  "VIT AP University, Amaravati",
  "SRM University AP, Amaravati",
  "KL Deemed to be University, Vijayawada",

  // --- WEST BENGAL, ODISHA & NORTH-EAST ---
  "IIT Kharagpur - Indian Institute of Technology",
  "NIT Durgapur - National Institute of Technology",
  "IIEST Shibpur - Indian Institute of Engineering Science and Technology",
  "Jadavpur University, Kolkata",
  "IEM Kolkata - Institute of Engineering and Management",
  "Heritage Institute of Technology, Kolkata",
  "Techno India University, Salt Lake Kolkata",
  "St. Xavier's College, Kolkata",
  "Calcutta University, Kolkata",
  "Presidency University, Kolkata",
  "MAKAUT - Maulana Abul Kalam Azad University of Technology, West Bengal",
  "IISER Kolkata - Indian Institute of Science Education and Research",
  "IIM Calcutta - Indian Institute of Management",
  "AIIMS Kalyani - All India Institute of Medical Sciences",
  "Medical College and Hospital, Kolkata",
  "IIT Bhubaneswar - Indian Institute of Technology",
  "NIT Rourkela - National Institute of Technology",
  "KIIT University, Bhubaneswar",
  "ITER - Siksha 'O' Anusandhan, Bhubaneswar",
  "Utkal University, Bhubaneswar",
  "VSSUT - Veer Surendra Sai University of Technology, Burla",
  "AIIMS Bhubaneswar - All India Institute of Medical Sciences",
  "IIT Guwahati - Indian Institute of Technology",
  "NIT Silchar - National Institute of Technology",
  "Gauhati University, Guwahati",
  "Tezpur University, Tezpur Assam",
  "Assam University, Silchar",
  "NIT Meghalaya - National Institute of Technology",
  "NEHU - North-Eastern Hill University, Shillong",
  "NIT Agartala - National Institute of Technology",
  "Sikkim Manipal University, Gangtok",

  // --- UTTARAKHAND & HIMACHAL PRADESH ---
  "IIT Roorkee - Indian Institute of Technology",
  "NIT Uttarakhand - National Institute of Technology",
  "GBPUAT - Govind Ballabh Pant University of Agriculture and Technology, Pantnagar",
  "Graphic Era Deemed to be University, Dehradun",
  "UPES - University of Petroleum and Energy Studies, Dehradun",
  "DIT University, Dehradun",
  "Forest Research Institute (FRI), Dehradun",
  "HNBGU - Hemvati Nandan Bahuguna Garhwal University, Srinagar Garhwal",
  "AIIMS Rishikesh - All India Institute of Medical Sciences",
  "IIT Mandi - Indian Institute of Technology",
  "NIT Hamirpur - National Institute of Technology",
  "HPU - Himachal Pradesh University, Shimla",
  "Shoolini University, Solan",
  "Jaypee University of Information Technology (JUIT), Waknaghat",

  // --- INTERNATIONAL UNIVERSITIES ---
  "Maseno University, Kenya"
];

